services:
  anonymization-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - anon-network
    depends_on:
      - research-db

networks:
  anon-network:
    driver: bridge